"""
Data module for compressed Speech BCI data.

This module provides data loaders for the compressed representations
generated by the hierarchical compressor.
"""

import os
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader, random_split
from Sentence import Sentence


class CompressedBCIDataset(Dataset):
    """
    Dataset for compressed BCI embeddings, ready for language model fine-tuning.
    """
    
    def __init__(self, compress_dir, etl_dir):
        """
        Initialize the compressed dataset.
        
        Args:
            compress_dir: Directory containing compressed embeddings
            etl_dir: Directory containing label data
        """
        self.compress_dir = compress_dir
        self.etl_dir = etl_dir
        
        # Initialize storage
        self.trial_ids = []     # Trial identifiers
        self.labels = []        # Text labels
        self.val_flag = []      # Validation flags
        
        # Load trial information
        self._load_trials()
        
        print(f"Loaded {len(self.trial_ids)} trials for compressed dataset")
        print(f"- Training: {len([f for f in self.val_flag if not f])}")
        print(f"- Validation: {len([f for f in self.val_flag if f])}")
    
    def _load_trials(self):
        """Load trial information and labels."""
        for split in ["train", "test"]:
            # Get list of trials in this split
            trial_dir = os.path.join(self.compress_dir, split)
            if not os.path.exists(trial_dir):
                raise ValueError(f"Directory not found: {trial_dir}")
            
            # List all trial files (*.pt files)
            trial_files = [f for f in os.listdir(trial_dir) if f.endswith(".pt")]
            
            for file in trial_files:
                # Extract trial ID (remove extension)
                trial_id = file.split(".")[0]
                
                # Construct path to label file
                label_file = os.path.join(self.etl_dir, f"{trial_id}_sentenceText.csv")
                
                # Load label text if available
                if os.path.exists(label_file):
                    text_data = Sentence()
                    text_data.load(label_file)
                    label_text = text_data.sentence_txt
                    
                    # Store trial information
                    self.trial_ids.append((split, trial_id))
                    self.labels.append(label_text)
                    self.val_flag.append(split == "test")
    
    def __len__(self):
        """Return the number of trials in the dataset."""
        return len(self.trial_ids)
    
    def __getitem__(self, idx):
        """
        Get compressed embeddings and label for a trial.
        
        Args:
            idx: Index of the trial
        
        Returns:
            Dictionary containing compressed embeddings and label
        """
        # Get trial information
        split, trial_id = self.trial_ids[idx]
        
        # Load compressed embeddings
        file_path = os.path.join(self.compress_dir, split, f"{trial_id}.pt")
        compressed_tokens = torch.load(file_path)
        
        # Return data
        return {
            "trial_id": trial_id,
            "compressed_tokens": compressed_tokens,  # Shape: [output_tokens, output_dim]
            "label": self.labels[idx],
            "is_validation": self.val_flag[idx]
        }


def create_data_loaders(compress_dir, etl_dir, batch_size=8, test_size=0.2, random_seed=42):
    """
    Create data loaders for training and validation.
    
    Args:
        compress_dir: Directory containing compressed embeddings
        etl_dir: Directory containing label data
        batch_size: Batch size for training
        test_size: Proportion of training data to use as validation
        random_seed: Random seed for reproducible splits
    
    Returns:
        Tuple of (train_loader, val_loader, test_loader)
    """
    # Create dataset
    dataset = CompressedBCIDataset(compress_dir, etl_dir)
    
    # Split into train, validation, and test sets
    train_indices = [i for i, is_val in enumerate(dataset.val_flag) if not is_val]
    test_indices = [i for i, is_val in enumerate(dataset.val_flag) if is_val]
    
    # Further split train set into train and validation
    train_size = int((1 - test_size) * len(train_indices))
    val_size = len(train_indices) - train_size
    
    # Create random generator with seed
    generator = torch.Generator().manual_seed(random_seed)
    
    # Perform the split
    train_subset_indices, val_subset_indices = random_split(
        train_indices, [train_size, val_size], generator=generator
    )
    
    # Convert indices back to lists
    train_subset_indices = [train_indices[i] for i in range(len(train_subset_indices))]
    val_subset_indices = [train_indices[i] for i in range(len(val_subset_indices))]
    
    # Create data loaders
    train_loader = DataLoader(
        dataset, batch_size=batch_size, shuffle=True,
        sampler=torch.utils.data.SubsetRandomSampler(train_subset_indices)
    )
    
    val_loader = DataLoader(
        dataset, batch_size=batch_size,
        sampler=torch.utils.data.SubsetRandomSampler(val_subset_indices)
    )
    
    test_loader = DataLoader(
        dataset, batch_size=batch_size,
        sampler=torch.utils.data.SubsetRandomSampler(test_indices)
    )
    
    return train_loader, val_loader, test_loader