"""
Data module for compressed Speech BCI data.

This module provides data loaders for the compressed representations
generated by the hierarchical compressor.
"""

import os
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader, random_split, Subset
from Sentence import Sentence


class CompressedBCIDataset(Dataset):
    """
    Dataset for compressed BCI embeddings, ready for language model fine-tuning.
    """
    
    def __init__(self, compress_dir, etl_dir):
        """
        Initialize the compressed dataset.
        
        Args:
            compress_dir: Directory containing compressed embeddings
            etl_dir: Directory containing label data
        """
        self.compress_dir = compress_dir
        self.etl_dir = etl_dir
        
        # Initialize storage
        self.trial_ids = []     # Trial identifiers
        self.labels = []        # Text labels
        self.val_flag = []      # Validation flags
        
        # Load trial information
        self._load_trials()
        
        print(f"Loaded {len(self.trial_ids)} trials for compressed dataset")
        print(f"- Training: {len([f for f in self.val_flag if not f])}")
        print(f"- Validation: {len([f for f in self.val_flag if f])}")
    
    def _load_trials(self):
        """Load trial information and labels."""
        for split in ["train", "test"]:
            # Get list of trials in this split
            trial_dir = os.path.join(self.compress_dir, split)
            if not os.path.exists(trial_dir):
                raise ValueError(f"Directory not found: {trial_dir}")
            
            # List all trial files (*.pt files)
            trial_files = [f for f in os.listdir(trial_dir) if f.endswith(".pt")]
            
            for file in trial_files:
                # Extract trial ID (remove extension)
                trial_id = file.split(".")[0]
                
                # Construct path to label file
                label_file = os.path.join(self.etl_dir, f"{trial_id}_sentenceText.csv")
                
                # Load label text if available
                if os.path.exists(label_file):
                    text_data = Sentence()
                    text_data.load(label_file)
                    label_text = text_data.sentence_txt
                    
                    # Store trial information
                    self.trial_ids.append((split, trial_id))
                    self.labels.append(label_text)
                    self.val_flag.append(split == "test")
    
    def __len__(self):
        """Return the number of trials in the dataset."""
        return len(self.trial_ids)
    
    def __getitem__(self, idx):
        """
        Get compressed embeddings and label for a trial.
        
        Args:
            idx: Index of the trial
        
        Returns:
            Dictionary containing compressed embeddings and label
        """
        # Get trial information
        split, trial_id = self.trial_ids[idx]
        
        # Load compressed embeddings
        file_path = os.path.join(self.compress_dir, split, f"{trial_id}.pt")
        compressed_tokens = torch.load(file_path)
        
        # Return data
        return {
            "trial_id": trial_id,
            "compressed_tokens": compressed_tokens,  # Shape: [output_tokens, output_dim]
            "label": self.labels[idx],
            "is_validation": self.val_flag[idx]
        }


def create_data_loaders(dataset, batch_size=8, test_size=0.2, random_seed=42):
    """
    Create data loaders for training, testing and validation.
    
    Args:
        dataset: CompressedBCIDataset instance
        batch_size: Batch size for training
        test_size: Proportion of non-validation data to use for testing
        random_seed: Random seed for reproducible splits
    
    Returns:
        Tuple of (train_loader, test_loader, val_loader)
    """

    # Split according to SpeechBCI requirements:
    # - "train" subdirectory data → Split into training and testing sets
    # - "test" subdirectory data → Used as validation set
    
    # Get indices for items from train directory (non-validation data)
    train_dir_indices = [i for i, is_val in enumerate(dataset.val_flag) if not is_val]
    
    # Get indices for items from test directory (validation data)
    val_indices = [i for i, is_val in enumerate(dataset.val_flag) if is_val]
    
    # Further split train directory data into actual training and testing sets
    train_size = int((1 - test_size) * len(train_dir_indices))
    test_size = len(train_dir_indices) - train_size
    
    print(f"Data split information:")
    print(f"- Total from train directory: {len(train_dir_indices)}")
    print(f"- Total from test directory (validation): {len(val_indices)}")
    print(f"- Training set size: {train_size}")
    print(f"- Testing set size: {test_size}")
    
    # Create random generator with seed
    generator = torch.Generator().manual_seed(random_seed)
    
    # Perform the split of train directory data
    train_subset, test_subset = random_split(
        train_dir_indices, [train_size, test_size], generator=generator
    )
    
    # Create subset datasets for each split
    train_dataset = Subset(dataset, list(train_subset))
    test_dataset = Subset(dataset, list(test_subset))
    val_dataset = Subset(dataset, val_indices)
    
    # Create data loaders
    train_loader = DataLoader(
        train_dataset, 
        batch_size=batch_size, 
        shuffle=True
    )
    
    test_loader = DataLoader(
        test_dataset, 
        batch_size=batch_size, 
        shuffle=False # No need to shuffle validation data
    )
    
    val_loader = DataLoader(
        val_dataset, 
        batch_size=batch_size, 
        shuffle=False  # No need to shuffle validation data
    )
    
    return train_loader, test_loader, val_loader